import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Script para ajustar o viewport só em ecrãs pequenos */}
        <Script
          id="mobile-viewport-fix"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
(function () {
  function updateViewport() {
    var meta = document.querySelector('meta[name="viewport"]');
    if (!meta) {
      meta = document.createElement('meta');
      meta.name = 'viewport';
      document.head.appendChild(meta);
    }

    if (window.innerWidth < 440) {
      meta.setAttribute('content', 'width=440');
    } else {
      meta.setAttribute('content', 'width=device-width, initial-scale=1');
    }
  }

  if (document.readyState === 'complete' || document.readyState === 'interactive') {
    updateViewport();
  } else {
    document.addEventListener('DOMContentLoaded', updateViewport);
  }

  window.addEventListener('resize', updateViewport);
})();
            `,
          }}
        />

        {children}
      </body>
    </html>
  );
}
